package com.smoothstack.lms.borrowermicroservice.depreciated.database;

import com.smoothstack.lms.borrowermicroservice.Debug;
import com.smoothstack.lms.borrowermicroservice.depreciated.database.sql.SQLDataMap;

import java.sql.*;
import java.util.*;
import java.util.function.Function;

public class DataAccess {

    private Connection connection = null;

    public DataAccess(Connection connection) {
        this.connection = connection;
    }

    public static <R> List<R> executeQuery(Connection connection, String sqlStatement, Function<ResultSet, R> extractor, Object... objects) throws SQLException {
        Debug.println("executeQuery:");
        PreparedStatement preparedStatement = getPreparedStatement(connection, sqlStatement, objects);

        ResultSet rs = preparedStatement.executeQuery();

        return extractResult(rs, extractor);
    }

    public static <R> List<R> executeQuery(Connection connection, String sqlStatement, Function<ResultSet, R> extractor, SQLDataMap dataMap) throws SQLException {
        Debug.println("executeQuery:");
        PreparedStatement preparedStatement = getPreparedStatement(connection, sqlStatement, dataMap);

        ResultSet rs = preparedStatement.executeQuery();

        return extractResult(rs, extractor);
    }

    public <R> List<R> executeQuery(String sqlStatement, Function<ResultSet, R> extractor, Object... objects) throws SQLException {
        return executeQuery(connection, sqlStatement, extractor, objects);
    }

    public <R> List<R> executeQuery(String sqlStatement, Function<ResultSet, R> extractor, SQLDataMap dataMap) throws SQLException {
        return executeQuery(connection, sqlStatement, extractor, dataMap);
    }

    public static PreparedStatement executeUpdate(Connection connection, String sqlStatement,  int autoGeneratedKeys, Object... objects) throws SQLException {
        Debug.println("executeUpdate:");
        PreparedStatement preparedStatement = getPreparedStatement(connection, sqlStatement, autoGeneratedKeys,objects);

        preparedStatement.executeUpdate();

        return preparedStatement;
    }

    public static PreparedStatement executeUpdate(Connection connection, String sqlStatement,  int autoGeneratedKeys, SQLDataMap dataMap) throws SQLException {
        Debug.println("executeUpdate:");
        PreparedStatement preparedStatement = getPreparedStatement(connection, sqlStatement, autoGeneratedKeys, dataMap);

        preparedStatement.executeUpdate();

        return preparedStatement;
    }

    public PreparedStatement executeUpdate(String sqlStatement, int autoGeneratedKeys, Object... objects) throws SQLException {
        return executeUpdate(connection, sqlStatement, autoGeneratedKeys, objects);
    }

    public PreparedStatement executeUpdate(String sqlStatement, int autoGeneratedKeys, SQLDataMap dataMap) throws SQLException {
        return executeUpdate(connection, sqlStatement, autoGeneratedKeys, dataMap);
    }

    public PreparedStatement executeUpdate(String sqlStatement, Object... objects) throws SQLException {
        return executeUpdate(connection, sqlStatement, Statement.NO_GENERATED_KEYS, objects);
    }

    public PreparedStatement executeUpdate(String sqlStatement, SQLDataMap dataMap) throws SQLException {
        return executeUpdate(connection, sqlStatement, Statement.NO_GENERATED_KEYS, dataMap);
    }


    public static PreparedStatement getPreparedStatement(Connection connection, String sqlStatement, int autoGeneratedKeys, Object... objects) throws SQLException {
        PreparedStatement preparedStatement = connection.prepareStatement(Debug.tee(sqlStatement), autoGeneratedKeys);

        List<Object> objectList = Arrays.asList(objects);
        for (int i = 0; i < objectList.size(); i++) {
            preparedStatement.setObject(1 + i, objectList.get(i));
            Debug.printf("-> ?[%d] = %s\n", 1 + i, objectList.get(i));
        }

        return preparedStatement;
    }

    public static PreparedStatement getPreparedStatement(Connection connection, String sqlStatement, int autoGeneratedKeys, SQLDataMap dataMap) throws SQLException {
        PreparedStatement preparedStatement = connection.prepareStatement(Debug.tee(sqlStatement), autoGeneratedKeys);

        String[] key = dataMap.keySet().toArray(new String[0]);

        for (int keyIndex = 0; keyIndex < key.length; keyIndex++) {
            preparedStatement.setObject(1 + keyIndex, dataMap.get(key[keyIndex]));
            Debug.printf("-> ?[%d] = %s\n", 1 + keyIndex, dataMap.get(key[keyIndex]));
        }

        return preparedStatement;
    }

    public static PreparedStatement getPreparedStatement(Connection connection, String sqlStatement, Object... objects) throws SQLException {
        return getPreparedStatement(connection, sqlStatement, Statement.NO_GENERATED_KEYS, objects);
    }

    public static PreparedStatement getPreparedStatement(Connection connection, String sqlStatement, SQLDataMap dataMap) throws SQLException {
        return getPreparedStatement(connection, sqlStatement, Statement.NO_GENERATED_KEYS, dataMap);
    }


    public PreparedStatement getPreparedStatement(String sqlStatement, int autoGeneratedKeys, Object... objects) throws SQLException {
        return getPreparedStatement(connection, sqlStatement, autoGeneratedKeys, objects);
    }

    public PreparedStatement getPreparedStatement(String sqlStatement, int autoGeneratedKeys, SQLDataMap dataMap) throws SQLException {
        return getPreparedStatement(connection, sqlStatement, autoGeneratedKeys, dataMap);
    }

    public PreparedStatement getPreparedStatement(String sqlStatement, Object... objects) throws SQLException {
        return getPreparedStatement(connection, sqlStatement, Statement.NO_GENERATED_KEYS, objects);
    }

    public PreparedStatement getPreparedStatement(String sqlStatement, SQLDataMap dataMap) throws SQLException {
        return getPreparedStatement(connection, sqlStatement, Statement.NO_GENERATED_KEYS, dataMap);
    }

    public static <R> List<R> extractResult(ResultSet rs, Function<ResultSet, R> extract) throws SQLException {
        Debug.println("extractResult:");
        List<R> resultList = new ArrayList<>();
        int i = 0;
        if (!rs.next()) {
            Debug.println("<- [no result returned]");
        } else {
            do {
                R result = extract.apply(rs);
                resultList.add(result);
                    Debug.printf("<- L[%d] = %s\n",i++, (result==null?"null":result.toString()));
            } while(rs.next());
        }

        return resultList;
    }

    public static void executePurge(Connection connection, String tableName) throws SQLException {
        String sqlStatement;
        PreparedStatement preparedStatement = connection.prepareStatement(
                sqlStatement = String.format("DELETE FROM %s",
                        tableName));
        Debug.println(sqlStatement);
        preparedStatement.executeUpdate();
        preparedStatement = connection.prepareStatement(
                sqlStatement = String.format("ALTER TABLE %s AUTO_INCREMENT = 1;",
                        tableName));
        Debug.println(sqlStatement);
        preparedStatement.executeUpdate();
    }

    public void executePurge(String tableName) throws SQLException {
        executePurge(connection, tableName);
    }

}
